<?php

declare(strict_types=1);

use Componenta\Http\Router\CompiledRoutes;
use Componenta\Http\Router\Cache\RouteCacheGenerator;
use Componenta\Http\Router\Exception\MethodNotAllowedException;
use Componenta\Http\Router\Exception\RouteNotFoundException;
use Componenta\Http\Router\Exception\RouteNotRegisteredException;
use Componenta\Http\Router\RouteRecord;
use Componenta\Http\Router\Routes;

// Cache file is pre-generated by: php tests/cache/generate.php
$cacheFile = __DIR__ . '/cache/compiled_routes.php';

beforeEach(function () use ($cacheFile) {
    $this->compiled = CompiledRoutes::fromCache($cacheFile);
});

// --- Static route matching ---

it('matches static route', function () {
    $result = $this->compiled->match($this->compiled, '/', 'GET');

    expect($result->name)->toBe('home')
        ->and($result->parameters)->toBe([]);
});

it('normalizes uri leading slash', function () {
    $result = $this->compiled->match($this->compiled, '', 'GET');

    expect($result->name)->toBe('home');
});

// --- Dynamic route matching ---

it('matches required parameter', function () {
    $result = $this->compiled->match($this->compiled, '/users/42', 'GET');

    expect($result->name)->toBe('user')
        ->and($result->parameters)->toBe(['id' => 42]);
});

it('casts numeric parameter to int', function () {
    $result = $this->compiled->match($this->compiled, '/users/123', 'GET');

    expect($result->parameters['id'])->toBe(123)
        ->and($result->parameters['id'])->toBeInt();
});

it('keeps string parameter as string', function () {
    $result = $this->compiled->match($this->compiled, '/posts/hello-world', 'GET');

    expect($result->parameters['slug'])->toBe('hello-world')
        ->and($result->parameters['slug'])->toBeString();
});

// --- Optional parameter matching ---

it('matches route without optional parameter', function () {
    $result = $this->compiled->match($this->compiled, '/archive', 'GET');

    expect($result->name)->toBe('archive')
        ->and($result->parameters)->toBe([]);
});

it('matches route with optional parameter present', function () {
    $result = $this->compiled->match($this->compiled, '/archive/2024', 'GET');

    expect($result->name)->toBe('archive')
        ->and($result->parameters)->toBe(['year' => 2024]);
});

it('uses default value for absent optional parameter', function () {
    $result = $this->compiled->match($this->compiled, '/items', 'GET');

    expect($result->parameters)->toBe(['page' => 1]);
});

it('matches mixed required and optional parameters', function () {
    $without = $this->compiled->match($this->compiled, '/blog/5', 'GET');
    $with = $this->compiled->match($this->compiled, '/blog/5/3', 'GET');

    expect($without->parameters)->toBe(['id' => 5])
        ->and($with->parameters)->toBe(['id' => 5, 'page' => 3]);
});

// --- Exception handling ---

it('throws RouteNotFoundException for unknown uri', function () {
    expect(fn () => $this->compiled->match($this->compiled, '/unknown', 'GET'))
        ->toThrow(RouteNotFoundException::class);
});

it('throws MethodNotAllowedException for static route', function () {
    expect(fn () => $this->compiled->match($this->compiled, '/', 'POST'))
        ->toThrow(MethodNotAllowedException::class);
});

it('throws MethodNotAllowedException for dynamic route', function () {
    expect(fn () => $this->compiled->match($this->compiled, '/users/1', 'DELETE'))
        ->toThrow(MethodNotAllowedException::class);
});

// --- URL generation ---

it('generates url for static route', function () {
    expect($this->compiled->generate($this->compiled, 'home'))->toBe('/');
});

it('generates url with required parameter', function () {
    expect($this->compiled->generate($this->compiled, 'user', ['id' => 42]))->toBe('/users/42');
});

it('generates url with optional parameter present', function () {
    expect($this->compiled->generate($this->compiled, 'archive', ['year' => 2024]))->toBe('/archive/2024');
});

it('generates url with optional parameter absent', function () {
    expect($this->compiled->generate($this->compiled, 'archive'))->toBe('/archive');
});

it('throws RouteNotRegisteredException for unknown name in generate', function () {
    expect(fn () => $this->compiled->generate($this->compiled, 'missing'))
        ->toThrow(RouteNotRegisteredException::class);
});

// --- Route collection ---

it('checks route existence by name', function () {
    expect($this->compiled->has('home'))->toBeTrue()
        ->and($this->compiled->has('missing'))->toBeFalse();
});

it('counts all routes', function () {
    expect($this->compiled->count())->toBe(10);
});

it('retrieves route record by name', function () {
    $route = $this->compiled->getRoute('user');

    expect($route->name)->toBe('user')
        ->and($route->methods)->toBe(['GET']);
});

it('throws RouteNotRegisteredException for unknown name in getRoute', function () {
    expect(fn () => $this->compiled->getRoute('missing'))
        ->toThrow(RouteNotRegisteredException::class);
});

it('iterates over all routes', function () {
    $names = [];
    foreach ($this->compiled as $name => $route) {
        $names[] = $name;
    }

    expect($names)->toHaveCount(10)
        ->and($names)->toContain('home', 'user', 'post', 'archive', 'api.users');
});

it('reuses route handler and middleware wrappers across repeated compiled matches', function () {
    $routes = new Routes();
    $routes->addRoute(RouteRecord::get(
        'cached',
        '/cached/{id}',
        'CachedController',
        ['AuthMiddleware', 'AuditMiddleware'],
    ));

    $file = tempnam(__DIR__ . '/cache', 'compiled_wrappers_');
    file_put_contents(
        $file,
        "<?php\n\ndeclare(strict_types=1);\n\nreturn " . var_export((new RouteCacheGenerator())->compile($routes), true) . ";\n",
    );

    try {
        $compiled = CompiledRoutes::fromCache($file);

        $first = $compiled->match($compiled, '/cached/1', 'GET');
        $second = $compiled->match($compiled, '/cached/2', 'GET');

        expect($second->handler)->toBe($first->handler)
            ->and($second->middlewares)->toBe($first->middlewares);
    } finally {
        @unlink($file);
    }
});

it('matches compiled dynamic routes when route names contain pcre mark syntax characters', function () {
    $routes = new Routes();
    $routes->addRoute(RouteRecord::get('posts.show)', '/posts/{id}', 'ShowPostController'));

    $file = tempnam(__DIR__ . '/cache', 'compiled_mark_chars_');
    file_put_contents(
        $file,
        "<?php\n\ndeclare(strict_types=1);\n\nreturn " . var_export((new RouteCacheGenerator())->compile($routes), true) . ";\n",
    );

    try {
        $compiled = CompiledRoutes::fromCache($file);

        $match = $compiled->match($compiled, '/posts/42', 'GET');

        expect($match->name)->toBe('posts.show)')
            ->and($match->parameters)->toBe(['id' => 42]);
    } finally {
        @unlink($file);
    }
});

it('preserves public and private middleware boundaries in compiled routes', function () {
    $authParsing = ['AuthenticationMiddleware', 'ProvideCurrentUserMiddleware', 'TouchSessionMiddleware'];

    $routes = new Routes();
    $api = $routes->group('api', '/api/v1', $authParsing);
    $api->get('posts', '/posts', 'PublicPostsController');

    $admin = $api->group('admin', '/admin', ['RequireAuthenticationMiddleware']);
    $admin->get('posts', '/posts', 'AdminPostsController');

    $file = tempnam(__DIR__ . '/cache', 'compiled_auth_');
    file_put_contents(
        $file,
        "<?php\n\ndeclare(strict_types=1);\n\nreturn " . var_export((new RouteCacheGenerator())->compile($routes), true) . ";\n",
    );

    try {
        $compiled = CompiledRoutes::fromCache($file);

        $public = $compiled->match($compiled, '/api/v1/posts', 'GET');
        $private = $compiled->match($compiled, '/api/v1/admin/posts', 'GET');

        expect($public->middlewares?->toArray())->toBe($authParsing)
            ->and($private->middlewares?->toArray())->toBe([
                ...$authParsing,
                'RequireAuthenticationMiddleware',
            ]);
    } finally {
        @unlink($file);
    }
});

// --- Groups ---

it('matches grouped route', function () {
    $result = $this->compiled->match($this->compiled, '/api/v1/users/42', 'GET');

    expect($result->name)->toBe('api.users')
        ->and($result->parameters)->toBe(['id' => 42]);
});

it('matches grouped route with optional parameter', function () {
    $without = $this->compiled->match($this->compiled, '/api/v1/posts', 'GET');
    $with = $this->compiled->match($this->compiled, '/api/v1/posts/5', 'GET');

    expect($without->name)->toBe('api.posts')
        ->and($without->parameters)->toBe([])
        ->and($with->parameters)->toBe(['id' => 5]);
});

// --- Behavioral parity with Routes ---

it('produces identical match results as Routes', function () {
    $routes = new Routes();
    $routes->addRoute(RouteRecord::get('home', '/', 'HomeController'));
    $routes->addRoute(RouteRecord::get('user', '/users/{id}', 'UserController'));
    $routes->addRoute(RouteRecord::get('post', '/posts/{slug}', 'PostController', tokens: ['slug' => '[a-z0-9-]+']));
    $routes->addRoute(RouteRecord::get('archive', '/archive/{year?}', 'ArchiveController', tokens: ['year' => '\d{4}']));
    $routes->addRoute(RouteRecord::post('create_post', '/posts', 'CreatePostController'));

    $cases = [
        ['/', 'GET'],
        ['/users/42', 'GET'],
        ['/posts/hello-world', 'GET'],
        ['/archive', 'GET'],
        ['/archive/2024', 'GET'],
        ['/posts', 'POST'],
    ];

    foreach ($cases as [$uri, $method]) {
        $fromRoutes = $routes->match($routes, $uri, $method);
        $fromCompiled = $this->compiled->match($this->compiled, $uri, $method);

        expect($fromCompiled->name)->toBe($fromRoutes->name)
            ->and($fromCompiled->parameters)->toBe($fromRoutes->parameters);
    }
});
