<?php

declare(strict_types=1);

use Componenta\Http\Router\Cache\RouteCacheGenerator;
use Componenta\Http\Router\CompiledRoutes;
use Componenta\Http\Router\Compiler;
use Componenta\Http\Router\RouteRecord;
use Componenta\Http\Router\Routes;

it('stores compact route references and restores omitted defaults', function () {
    $routes = new Routes();
    $routes->addRoute(RouteRecord::get('home.compact', '/', 'HomeController'));
    $routes->addRoute(RouteRecord::post('posts.create', '/posts', 'CreatePostController'));
    $routes->addRoute(RouteRecord::get('users.show', '/users/{id}', 'ShowUserController'));

    $data = (new RouteCacheGenerator())->compile($routes);
    $compiler = new Compiler();

    expect($data['version'])->toBe(RouteCacheGenerator::CACHE_VERSION)
        ->and($data['staticRoutes']['GET']['/'])->toBe('home.compact')
        ->and($data['staticRoutes']['POST']['/posts'])->toBe('posts.create')
        ->and($data['routeMap']['GET']['r0'])->toBe('users.show')
        ->and($data['routeData']['home.compact'])->toBe([
            'path' => '/',
            'handler' => 'HomeController',
        ])
        ->and($data['routeData']['posts.create']['methods'])->toBe(['POST'])
        ->and($data['routeData']['users.show'])->not->toHaveKey('tokens')
        ->and($data)->not->toHaveKey('defaultTokens');

    $file = tempnam(sys_get_temp_dir(), 'componenta_routes_');
    file_put_contents($file, '<?php return ' . var_export($data, true) . ';');

    try {
        $compiled = CompiledRoutes::fromCache($file);

        expect($compiled->match($compiled, '/', 'GET')->name)->toBe('home.compact')
            ->and($compiled->getRoute('home.compact')->methods)->toBe(['GET'])
            ->and($compiled->getRoute('home.compact')->tokens)->toBe($compiler->compile('/')->tokens)
            ->and($compiled->getRoute('home.compact')->middlewares)->toBeNull()
            ->and($compiled->getRoute('posts.create')->methods)->toBe(['POST'])
            ->and($compiled->match($compiled, '/users/42', 'GET')->parameters)->toBe(['id' => 42])
            ->and($compiled->generate($compiled, 'users.show', ['id' => 42]))->toBe('/users/42');
    } finally {
        @unlink($file);
    }
});

it('omits empty top-level cache sections and loads an empty cache', function () {
    $generator = new RouteCacheGenerator();
    $routes = new Routes();
    $cacheFile = tempnam(sys_get_temp_dir(), 'componenta_empty_routes_');

    if ($cacheFile === false) {
        throw new RuntimeException('Unable to create a temporary route cache.');
    }

    try {
        $generator->generate($routes, $cacheFile);

        expect(require $cacheFile)->toBe([])
            ->and(CompiledRoutes::fromCache($cacheFile))->toHaveCount(0);

        $routes->addRoute(RouteRecord::get('home', '/', 'HomeController'));

        expect(array_keys($generator->compile($routes)))->toBe([
            'version',
            'staticRoutes',
            'routeData',
        ]);
    } finally {
        @unlink($cacheFile);
    }
});

it('loads route caches generated by the legacy embedded-record format', function () {
    $legacyRoute = [
        'name' => 'legacy.home',
        'path' => '/',
        'handler' => 'LegacyHomeController',
        'methods' => ['GET'],
        'middlewares' => [],
        'tokens' => [],
        'defaults' => [],
        'paramNames' => [],
        'optionalParams' => [],
        'group' => null,
    ];

    $data = [
        'staticRoutes' => ['GET' => ['/' => $legacyRoute]],
        'routeData' => ['legacy.home' => $legacyRoute],
        'regex' => [],
        'routeMap' => [],
    ];

    $file = tempnam(sys_get_temp_dir(), 'componenta_legacy_routes_');
    file_put_contents($file, '<?php return ' . var_export($data, true) . ';');

    try {
        $compiled = CompiledRoutes::fromCache($file);

        expect($compiled->match($compiled, '/', 'GET')->name)->toBe('legacy.home')
            ->and($compiled->getRoute('legacy.home')->name)->toBe('legacy.home')
            ->and($compiled->getRoute('legacy.home')->tokens)->toBe([]);
    } finally {
        @unlink($file);
    }
});
