<?php

declare(strict_types=1);

namespace Componenta\Http\Router;

use Componenta\Http\Middleware\MiddlewareGroup;
use Componenta\Http\Router\Cache\RouteCacheGenerator;
use Componenta\Http\Router\Contract\CompilerInterface;
use Componenta\Http\Router\Contract\GeneratorInterface;
use Componenta\Http\Router\Contract\MatcherInterface;
use Componenta\Http\Router\Contract\RouteCollectorInterface;
use Componenta\Http\Router\Contract\SyntaxConverterInterface;
use Componenta\Http\Router\Contract\SyntaxParserInterface;
use Componenta\Http\Router\Exception\MethodNotAllowedException;
use Componenta\Http\Router\Exception\RouteNotFoundException;
use Componenta\Http\Router\Exception\RouteNotRegisteredException;
use Componenta\Http\Router\Syntax\ColonSyntax;
use Componenta\Http\Router\Syntax\AngleBracketSyntax;
use Componenta\Http\Router\Syntax\CompositeSyntax;
use Componenta\Http\Router\Syntax\CurlySyntax;
use Componenta\Http\Router\Syntax\SquareBracketSyntax;
use Componenta\Http\Router\Syntax\SyntaxConverter;
use Generator;

/**
 * Optimized route collection for production.
 *
 * Performance characteristics:
 * - Static routes: O(1) hash lookup, zero regex
 * - Dynamic routes (unified regex): O(1) single regex match
 * - Dynamic routes (chunks): O(k) where k = relevant chunks
 * - Cached RouteRecord instances for public access
 * - Pre-compiled regex patterns in cache
 * - Retains source syntax for URL generation
 */
final class CompiledRoutes implements RouteCollectorInterface, MatcherInterface, GeneratorInterface
{
    use ParameterCaster;

    private readonly ColonSyntax $syntax;
    private readonly SyntaxParserInterface $sourceSyntax;
    private readonly CompilerInterface $cachedCompiler;
    private ?Routes $runtimeRoutes = null;
    private bool $matchingStarted = false;
    private bool $runtimeMatching = false;
    public CompilerInterface $compiler;
    public SyntaxConverterInterface $syntaxConverter;

    /** @var array<string, RouteHandler> */
    private array $handlers = [];

    /** @var array<string, RouteRecord> */
    private array $records = [];

    /** @var array<string, MiddlewareGroup|null> */
    private array $middlewares = [];

    /** @param array<string, string> $defaultTokens */
    private function __construct(
        private readonly array $staticRoutes,
        private readonly array $regex,
        private readonly array $routeMap,
        private readonly array $dynamicChunks,
        private readonly array $prefixIndex,
        private readonly array $defaultTokens,
        private readonly array $routeData,
        private readonly bool $useSourceMatching = false,
        ?SyntaxParserInterface $generationSyntax = null,
        ?SyntaxParserInterface $compilerSyntax = null,
        private readonly bool $explicitGenerationSyntax = true,
    ) {
        $this->syntax = new ColonSyntax();
        $this->sourceSyntax = $generationSyntax ?? new CompositeSyntax();
        $this->compiler = new Compiler($compilerSyntax, $defaultTokens);
        $this->cachedCompiler = new Compiler($compilerSyntax, $defaultTokens);
        $this->syntaxConverter = new SyntaxConverter();
    }

    /**
     * @param array{name: string, handler: mixed} $route
     */
    private function handlerFor(array $route): RouteHandler
    {
        $name = $route['name'];

        return $this->handlers[$name] ??= $route['handler'] instanceof RouteHandler
            ? $route['handler']
            : new RouteHandler($route['handler']);
    }

    /**
     * @param array{name: string, middlewares?: array} $route
     */
    private function middlewaresFor(array $route): ?MiddlewareGroup
    {
        $name = $route['name'];

        if (array_key_exists($name, $this->middlewares)) {
            return $this->middlewares[$name];
        }

        $middlewares = $route['middlewares'] ?? [];

        return $this->middlewares[$name] = $middlewares === []
            ? null
            : MiddlewareGroup::fromArray($middlewares);
    }

    /**
     * @param array{name: string, handler: mixed, middlewares?: array} $route
     * @param array<string, mixed> $parameters
     */
    private function matchResult(array $route, array $parameters): MatchResult
    {
        return new MatchResult(
            $route['name'],
            $this->handlerFor($route),
            $this->middlewaresFor($route),
            $parameters,
            $this,
        );
    }

    /**
     * Resolve compact route-name references while accepting legacy embedded
     * route arrays generated by previous framework versions.
     *
     * @return array{name: string, path: string, handler: mixed, ...}
     */
    private function routeFor(mixed $reference): array
    {
        if (is_array($reference)) {
            return $reference;
        }

        if (!is_string($reference) || !isset($this->routeData[$reference])) {
            throw new \LogicException(sprintf('Compiled route reference "%s" is invalid.', get_debug_type($reference)));
        }

        return $this->routeDataFor($reference);
    }

    /** @return array{name: string, path: string, handler: mixed, record?: array{path: string, ...}, defaults?: array<string, mixed>, tokens?: array<string, string>, optionalParams?: array<string, mixed>, ...} */
    private function routeDataFor(string $name): array
    {
        if (!isset($this->routeData[$name])) {
            throw new \LogicException(sprintf('Compiled route data for "%s" is missing.', $name));
        }

        return ['name' => $name] + $this->routeData[$name];
    }

    /** @return array{name: string, path: string, handler: mixed, tokens: array} */
    private function routeRecordDataFor(string $name): array
    {
        $data = $this->routeDataFor($name);
        if (isset($data['record'])) {
            return array_replace($data, $data['record']);
        }
        $data['tokens'] = [
            ...$this->defaultTokens,
            ...($data['tokens'] ?? []),
        ];

        return $data;
    }

    /**
     * Create instance from cache file.
     *
     * @param string $cacheFile Path to cache file generated by RouteCacheGenerator
     */
    public static function fromCache(string $cacheFile): self
    {
        return self::fromArray(require $cacheFile);
    }

    public static function fromArray(array $data): self
    {
        return new self(
            $data['staticRoutes'] ?? [],
            $data['regex'] ?? [],
            $data['routeMap'] ?? [],
            $data['dynamicChunks'] ?? [],
            $data['prefixIndex'] ?? [],
            in_array($data['version'] ?? null, [4, 5, 6, 7, RouteCacheGenerator::CACHE_VERSION], true)
                ? ($data['defaultTokens'] ?? CompilerInterface::DEFAULT_PATTERNS)
                : [],
            $data['routeData'] ?? [],
            ($data['version'] ?? null) === 4,
            self::syntaxFromCache(array_key_exists('generationSyntax', $data) ? $data['generationSyntax'] : CompositeSyntax::class),
            self::syntaxFromCache(array_key_exists('compilerSyntax', $data) ? $data['compilerSyntax'] : CompositeSyntax::class),
            $data['explicitGenerationSyntax'] ?? (($data['version'] ?? 0) < 8),
        );
    }

    private static function syntaxFromCache(mixed $syntax): SyntaxParserInterface
    {
        return match ($syntax) {
            CompositeSyntax::class => new CompositeSyntax(),
            CurlySyntax::class => new CurlySyntax(),
            SquareBracketSyntax::class => new SquareBracketSyntax(),
            AngleBracketSyntax::class => new AngleBracketSyntax(),
            ColonSyntax::class => new ColonSyntax(),
            default => throw new \InvalidArgumentException('Unknown route cache syntax.'),
        };
    }

    /** Invalid or missing generated data leaves runtime resolution to the source. */
    public static function tryFromCache(string $file): ?self
    {
        if (!is_file($file) || !is_readable($file)) { return null; }
        set_error_handler(static function (int $severity, string $message, string $file, int $line): never {
            throw new \ErrorException($message, 0, $severity, $file, $line);
        });
        try {
            $data = (static fn (string $file): mixed => require $file)($file);
            return self::fromCacheData($data);
        } catch (\Throwable) {
            return null;
        } finally {
            restore_error_handler();
        }
    }

    private static function fromCacheData(mixed $data): ?self
    {
        if (!is_array($data) || ($data['version'] ?? null) !== RouteCacheGenerator::CACHE_VERSION) {
            return null;
        }
        if (array_key_exists('explicitGenerationSyntax', $data) && !is_bool($data['explicitGenerationSyntax'])) { return null; }
        foreach (['staticRoutes', 'regex', 'routeMap', 'dynamicChunks', 'prefixIndex', 'defaultTokens', 'routeData'] as $key) {
            if (isset($data[$key]) && !is_array($data[$key])) { return null; }
        }
        if (!self::isTokenMap($data['defaultTokens'] ?? [])) { return null; }
        foreach ($data['routeData'] ?? [] as $name => $route) {
            if (!is_array($route) || !is_string($route['path'] ?? null)
                || !array_key_exists('handler', $route) || !is_array($route['record'] ?? null)
                || !is_string($route['record']['path'] ?? null)
                || !is_array($route['record']['tokens'] ?? null) || !is_array($route['record']['defaults'] ?? null)) {
                return null;
            }
            foreach (['methods', 'middlewares', 'tokens', 'defaults', 'paramNames', 'optionalParams'] as $key) {
                if (isset($route[$key]) && !is_array($route[$key])) { return null; }
            }
            if (!self::isTokenMap($route['tokens'] ?? []) || !self::isTokenMap($route['optionalParams'] ?? [], true)) {
                return null;
            }
            $paramNames = $route['paramNames'] ?? [];
            if (!array_is_list($paramNames)) { return null; }
            foreach ($paramNames as $paramName) {
                if (!is_string($paramName) || $paramName === '') { return null; }
            }
            if (count(array_unique($paramNames)) !== count($paramNames)) { return null; }
            foreach ($route['defaults'] ?? [] as $paramName => $value) {
                if (!is_string($paramName) || $paramName === '' || (!is_scalar($value) && $value !== null)) { return null; }
            }
            RouteRecord::fromArray(array_replace(['name' => (string) $name] + $route, $route['record']));
        }
        // Check all indexes and regular expressions before exposing any compiled collection.
        $known = static fn (mixed $name): bool => is_string($name) && isset($data['routeData'][$name]);
        foreach ($data['staticRoutes'] ?? [] as $entries) {
            if (!is_array($entries)) { return null; }
            foreach ($entries as $name) { if (!$known($name)) { return null; } }
        }
        foreach ($data['regex'] ?? [] as $method => $regex) {
            if (!is_string($regex) || preg_match($regex, '') === false || !is_array($data['routeMap'][$method] ?? null)) { return null; }
            foreach ($data['routeMap'][$method] as $name) { if (!$known($name)) { return null; } }
        }
        foreach ($data['dynamicChunks'] ?? [] as $method => $chunks) {
            if (!is_array($chunks)) { return null; }
            foreach ($chunks as $chunk) {
                if (!is_array($chunk) || !is_string($chunk['regex'] ?? null) || preg_match($chunk['regex'], '') === false
                    || !is_array($chunk['routeMap'] ?? null)) { return null; }
                foreach ($chunk['routeMap'] as $name) { if (!$known($name)) { return null; } }
            }
        }
        foreach ($data['prefixIndex'] ?? [] as $method => $prefixes) {
            if (!is_array($prefixes)) { return null; }
            foreach ($prefixes as $indexes) {
                if (!is_array($indexes)) { return null; }
                foreach ($indexes as $index) {
                    if (!is_int($index) || !isset($data['dynamicChunks'][$method][$index])) { return null; }
                }
            }
        }
        return self::fromArray($data);
    }

    private static function isTokenMap(array $tokens, bool $nullable = false): bool
    {
        foreach ($tokens as $name => $pattern) {
            if (!is_string($name) || $name === '' || (!is_string($pattern) && !($nullable && $pattern === null))) {
                return false;
            }
            if ($pattern !== null && preg_match('#^' . $pattern . '$#', '') === false) {
                return false;
            }
        }
        return true;
    }

    /**
     * Match URI against routes.
     *
     * @param RouteCollectorInterface $routes Route collection (should be $this for optimal performance)
     * @param string $uri URI to match
     * @param string $method HTTP method
     * @return MatchResult Match result with route and parameters
     * @throws MethodNotAllowedException If URI matches but method not allowed
     * @throws RouteNotFoundException If no route matches
     */
    public function match(RouteCollectorInterface $routes, string $uri, string $method): MatchResult
    {
        if ($routes !== $this) {
            return $routes instanceof MatcherInterface
                ? $routes->match($routes, $uri, $method)
                : $this->matchGeneric($routes, $uri, $method);
        }

        if (!$this->matchingStarted) {
            // Like Routes, matching keeps the compiler used to create its first index.
            $this->runtimeMatching = $this->compiler != $this->cachedCompiler;
            $this->matchingStarted = true;
        }
        if ($this->runtimeMatching) {
            $source = $this->runtimeRoutes();
            return $source->match($source, $uri, $method);
        }

        $method = strtoupper($method);

        $uri = '/' . ltrim($uri, '/');

        // Version 4 can combine expressions whose MARK metadata overwrites a route parameter.
        if ($this->useSourceMatching) {
            return $this->matchSourcePatterns($uri, $method);
        }

        // Static route lookup - O(1)
        if (isset($this->staticRoutes[$method][$uri])) {
            return $this->matchResult($this->routeFor($this->staticRoutes[$method][$uri]), []);
        }

        // Dynamic matching - unified regex or chunks
        $allowed = [];
        $result = $this->regex !== []
            ? $this->matchUnifiedRegex($uri, $method, $allowed)
            : $this->matchChunks($uri, $method, $allowed);

        if ($result !== null) {
            return $result;
        }

        // Collect allowed methods for static routes only on miss
        foreach ($this->staticRoutes as $m => $uris) {
            if (isset($uris[$uri])) {
                $allowed[] = $m;
            }
        }

        if ($allowed !== []) {
            $allowed = array_values(array_unique($allowed));
            sort($allowed, SORT_STRING);
            throw new MethodNotAllowedException($uri, $method, $allowed);
        }

        throw new RouteNotFoundException($uri, $method);
    }

    /**
     * Match against unified regex (single pattern per HTTP method).
     *
     * @param string $uri URI to match
     * @param string $method HTTP method
     * @param array $allowed Allowed methods collector (by reference)
     * @return MatchResult|null Match result or null if not matched
     */
    private function matchUnifiedRegex(string $uri, string $method, array &$allowed): ?MatchResult
    {
        if (isset($this->regex[$method])) {
            $map = $this->routeMap[$method];
            $matched = preg_match($this->regex[$method], $uri, $m);
            if ($matched === false && count($map) > 1) {
                return $this->matchSourcePatterns($uri, $method);
            }
            if ($matched === 1) {
                $d = $this->routeFor(count($map) === 1 ? reset($map) : $map[$m['MARK']]);
                return $this->matchResult($d, $this->extractParams($m, $d));
            }
        }

        foreach ($this->regex as $m => $regex) {
            if ($m === $method) { continue; }
            $matched = preg_match($regex, $uri);
            if ($matched === false && count($this->routeMap[$m]) > 1) {
                return $this->matchSourcePatterns($uri, $method);
            }
            if ($matched === 1) {
                $allowed[] = $m;
            }
        }

        return null;
    }

    /**
     * Match against chunked regex patterns.
     *
     * Uses prefix index to reduce chunks to search.
     *
     * @param string $uri URI to match
     * @param string $method HTTP method
     * @param array $allowed Allowed methods collector (by reference)
     * @return MatchResult|null Match result or null if not matched
     */
    private function matchChunks(string $uri, string $method, array &$allowed): ?MatchResult
    {
        if (isset($this->dynamicChunks[$method])) {
            $prefix = ($p = strpos($uri, '/', 1)) !== false ? substr($uri, 1, $p - 1) : substr($uri, 1);

            $chunksToSearch = array_values(array_unique([
                ...($this->prefixIndex[$method][$prefix] ?? []),
                ...($this->prefixIndex[$method]['*'] ?? []),
            ]));

            if ($chunksToSearch === []) {
                $chunksToSearch = array_keys($this->dynamicChunks[$method]);
            } else {
                sort($chunksToSearch);
            }

            foreach ($chunksToSearch as $chunkIndex) {
                if (!isset($this->dynamicChunks[$method][$chunkIndex])) {
                    continue;
                }

                $chunk = $this->dynamicChunks[$method][$chunkIndex];

                $map = $chunk['routeMap'];
                $matched = preg_match($chunk['regex'], $uri, $m);
                if ($matched === false && count($map) > 1) {
                    return $this->matchSourcePatterns($uri, $method);
                }
                if ($matched === 1) {
                    $d = $this->routeFor(count($map) === 1 ? reset($map) : $map[$m['MARK']]);
                    return $this->matchResult($d, $this->extractParams($m, $d));
                }
            }
        }

        foreach ($this->dynamicChunks as $m => $methodChunks) {
            if ($m === $method) {
                continue;
            }
            foreach ($methodChunks as $chunk) {
                $matched = preg_match($chunk['regex'], $uri);
                if ($matched === false && count($chunk['routeMap']) > 1) {
                    return $this->matchSourcePatterns($uri, $method);
                }
                if ($matched === 1) {
                    $allowed[] = $m;
                    break;
                }
            }
        }

        return null;
    }

    private function matchSourcePatterns(string $uri, string $method): MatchResult
    {
        // Combined expressions can exhaust PCRE limits before individual routes do.
        $source = new Routes($this->cachedCompiler);
        foreach ($this as $route) {
            $source->addRoute($route);
        }

        return $source->match($source, $uri, $method);
    }

    /**
     * Extract matched parameters with type coercion.
     *
     * Numeric strings are converted to integers or floats.
     *
     * @param array $matches Regex matches
     * @param array $routeData Route data with paramNames and defaults
     * @return array<string, mixed> Extracted parameters
     */
    private function extractParams(array $matches, array $routeData): array
    {
        $params = $routeData['defaults'] ?? [];

        foreach ($routeData['paramNames'] ?? [] as $name) {
            if (isset($matches[$name]) && $matches[$name] !== '') {
                $params[$name] = $this->castParameter($matches[$name]);
            }
        }

        return $params;
    }

    /**
     * Match against non-compiled route collection.
     *
     * Fallback for when routes !== $this. Compiles routes on-the-fly.
     *
     * @param RouteCollectorInterface $routes Route collection
     * @param string $uri URI to match
     * @param string $method HTTP method
     * @return MatchResult Match result
     * @throws MethodNotAllowedException If URI matches but method not allowed
     * @throws RouteNotFoundException If no route matches
     */
    private function matchGeneric(RouteCollectorInterface $routes, string $uri, string $method): MatchResult
    {
        $method = strtoupper($method);
        $uri = '/' . ltrim($uri, '/');
        $allowed = [];

        foreach ($routes as $route) {
            $compiled = $this->compiler->compile(
                $route->path,
                $route->tokens,
                $route->defaults
            );

            if (!$compiled->hasParameters()) {
                if ($route->path === $uri) {
                    if ($route->allow($method)) {
                        return new MatchResult($route->name, $route->handler, $route->middlewares, [], $route);
                    }
                    array_push($allowed, ...$route->methods);
                }
            } elseif (preg_match('#^' . $compiled->regex . '$#', $uri, $m)) {
                if ($route->allow($method)) {
                    $params = $compiled->defaults;
                    foreach ($compiled->parameterNames() as $name) {
                        if (isset($m[$name]) && $m[$name] !== '') {
                            $params[$name] = $this->castParameter($m[$name]);
                        }
                    }
                    return new MatchResult($route->name, $route->handler, $route->middlewares, $params, $route);
                }
                array_push($allowed, ...$route->methods);
            }
        }

        if ($allowed !== []) {
            $allowed = array_values(array_unique($allowed));
            sort($allowed, SORT_STRING);
            throw new MethodNotAllowedException($uri, $method, $allowed);
        }
        throw new RouteNotFoundException($uri, $method);
    }

    /**
     * Generate URL for named route.
     *
     * @param RouteCollectorInterface $routes Route collection (should be $this for optimal performance)
     * @param string $name Route name
     * @param array<string, mixed> $parameters Route parameters
     * @return string Generated URL
     * @throws RouteNotRegisteredException If route not found
     */
    public function generate(RouteCollectorInterface $routes, string $name, array $parameters = []): string
    {
        if ($routes !== $this) {
            return $routes instanceof GeneratorInterface
                ? $routes->generate($routes, $name, $parameters)
                : $this->generateFromRoute($routes->getRoute($name), $parameters);
        }

        if ($this->compiler != $this->cachedCompiler) {
            $source = $this->runtimeRoutes();
            return $source->generate($source, $name, $parameters);
        }

        if (!isset($this->routeData[$name])) {
            throw new RouteNotRegisteredException($name);
        }

        $d = $this->routeDataFor($name);

        $hasSource = isset($d['record']);
        $path = $hasSource ? $d['record']['path'] : $d['path'];
        $syntax = $hasSource ? $this->sourceSyntax : $this->syntax;

        if (!$hasSource && !$syntax->hasParameter($path)) {
            return $path;
        }

        return $syntax->buildPath(
            $path,
            $parameters + ($d['defaults'] ?? []),
            [
                ...$this->defaultTokens,
                ...($d['tokens'] ?? []),
            ],
            $d['optionalParams'] ?? [],
            $name
        );
    }

    private function runtimeRoutes(): Routes
    {
        if ($this->runtimeRoutes === null) {
            $this->runtimeRoutes = new Routes($this->compiler, $this->explicitGenerationSyntax ? $this->sourceSyntax : null);
            foreach ($this as $route) {
                $this->runtimeRoutes->addRoute($route);
            }
        }
        $this->runtimeRoutes->compiler = $this->compiler;
        return $this->runtimeRoutes;
    }

    /**
     * Generate URL from non-cached route.
     *
     * Compiles route on-the-fly and preserves its generation syntax.
     *
     * @param RouteRecord $route Route record
     * @param array<string, mixed> $parameters Route parameters
     * @return string Generated URL
     */
    private function generateFromRoute(RouteRecord $route, array $parameters): string
    {
        $compiled = $this->compiler->compile(
            $route->path,
            $route->tokens,
            $route->defaults
        );

        $syntax = $this->explicitGenerationSyntax ? $this->sourceSyntax
            : ($this->compiler instanceof Compiler ? $this->compiler->syntax : new CompositeSyntax());

        return $syntax->buildPath(
            $route->path,
            $parameters + $compiled->defaults,
            $compiled->tokens,
            $compiled->optionalParameters,
            $route->name
        );
    }

    /**
     * Check if route exists by name.
     */
    public function has(string $name): bool
    {
        return isset($this->routeData[$name]);
    }

    /**
     * Get route by name.
     *
     * @throws RouteNotRegisteredException If route not found
     */
    public function getRoute(string $name): RouteRecord
    {
        if (!isset($this->routeData[$name])) {
            throw new RouteNotRegisteredException($name);
        }

        if (!isset($this->records[$name])) {
            $data = $this->routeRecordDataFor($name);
            $data['handler'] = $this->handlerFor($data);
            $data['middlewares'] = $this->middlewaresFor($data) ?? [];
            $this->records[$name] = RouteRecord::fromArray($data);
        }

        return $this->records[$name];
    }

    /**
     * Iterate over all routes.
     *
     * @return Generator<string, RouteRecord>
     */
    public function getIterator(): Generator
    {
        foreach ($this->routeData as $name => $data) {
            yield $name => $this->getRoute((string) $name);
        }
    }

    /**
     * Get total route count.
     */
    public function count(): int
    {
        return count($this->routeData);
    }

    /**
     * Convert to array of route records.
     *
     * @return array<string, RouteRecord>
     */
    public function toArray(): array
    {
        $routes = [];
        foreach ($this->routeData as $name => $_) {
            $routes[$name] = $this->getRoute((string) $name);
        }

        return $routes;
    }
}
