<?php

declare(strict_types=1);

namespace Componenta\Http\Router;

use Componenta\Http\Middleware\MiddlewareGroup;
use Componenta\Http\Router\Contract\CompilerInterface;
use Componenta\Http\Router\Contract\GeneratorInterface;
use Componenta\Http\Router\Contract\MatcherInterface;
use Componenta\Http\Router\Contract\RouteCollectorInterface;
use Componenta\Http\Router\Contract\SyntaxConverterInterface;
use Componenta\Http\Router\Exception\MethodNotAllowedException;
use Componenta\Http\Router\Exception\RouteNotFoundException;
use Componenta\Http\Router\Exception\RouteNotRegisteredException;
use Componenta\Http\Router\Syntax\ColonSyntax;
use Componenta\Http\Router\Syntax\SyntaxConverter;
use Generator;

/**
 * Optimized route collection for production.
 *
 * Performance characteristics:
 * - Static routes: O(1) hash lookup, zero regex
 * - Dynamic routes (unified regex): O(1) single regex match
 * - Dynamic routes (chunks): O(k) where k = relevant chunks
 * - Lazy RouteRecord initialization (PHP 8.4 lazy objects)
 * - Pre-compiled regex patterns in cache
 * - Always uses ColonSyntax for fastest URL generation
 */
final class CompiledRoutes implements RouteCollectorInterface, MatcherInterface, GeneratorInterface
{
    use ParameterCaster;

    private readonly ColonSyntax $syntax;
    public CompilerInterface $compiler;
    public SyntaxConverterInterface $syntaxConverter;

    /** @var array<string, RouteHandler> */
    private array $handlers = [];

    /** @var array<string, MiddlewareGroup|null> */
    private array $middlewares = [];

    private function __construct(
        private readonly array $staticRoutes,
        private readonly array $regex,
        private readonly array $routeMap,
        private readonly array $dynamicChunks,
        private readonly array $prefixIndex,
        private readonly array $routeData,
    ) {
        $this->syntax = new ColonSyntax();
        $this->compiler = new Compiler();
        $this->syntaxConverter = new SyntaxConverter();
    }

    /**
     * @param array{name: string, handler: mixed} $route
     */
    private function handlerFor(array $route): RouteHandler
    {
        $name = $route['name'];

        return $this->handlers[$name] ??= $route['handler'] instanceof RouteHandler
            ? $route['handler']
            : new RouteHandler($route['handler']);
    }

    /**
     * @param array{name: string, middlewares?: array} $route
     */
    private function middlewaresFor(array $route): ?MiddlewareGroup
    {
        $name = $route['name'];

        if (array_key_exists($name, $this->middlewares)) {
            return $this->middlewares[$name];
        }

        $middlewares = $route['middlewares'] ?? [];

        return $this->middlewares[$name] = $middlewares === []
            ? null
            : MiddlewareGroup::fromArray($middlewares);
    }

    /**
     * @param array{name: string, handler: mixed, middlewares?: array} $route
     * @param array<string, mixed> $parameters
     */
    private function matchResult(array $route, array $parameters): MatchResult
    {
        return new MatchResult(
            $route['name'],
            $this->handlerFor($route),
            $this->middlewaresFor($route),
            $parameters,
            $this,
        );
    }

    /**
     * Create instance from cache file.
     *
     * @param string $cacheFile Path to cache file generated by RouteCacheGenerator
     */
    public static function fromCache(string $cacheFile): self
    {
        $data = require $cacheFile;

        return new self(
            $data['staticRoutes'],
            $data['regex'] ?? [],
            $data['routeMap'] ?? [],
            $data['dynamicChunks'] ?? [],
            $data['prefixIndex'] ?? [],
            $data['routeData'],
        );
    }

    /**
     * Match URI against routes.
     *
     * @param RouteCollectorInterface $routes Route collection (should be $this for optimal performance)
     * @param string $uri URI to match
     * @param string $method HTTP method
     * @return MatchResult Match result with route and parameters
     * @throws MethodNotAllowedException If URI matches but method not allowed
     * @throws RouteNotFoundException If no route matches
     */
    public function match(RouteCollectorInterface $routes, string $uri, string $method): MatchResult
    {
        if ($routes !== $this) {
            return $routes instanceof MatcherInterface
                ? $routes->match($routes, $uri, $method)
                : $this->matchGeneric($routes, $uri, $method);
        }

        $method = strtoupper($method);

        $uri = '/' . ltrim($uri, '/');

        // Static route lookup - O(1)
        if (isset($this->staticRoutes[$method][$uri])) {
            return $this->matchResult($this->staticRoutes[$method][$uri], []);
        }

        // Dynamic matching - unified regex or chunks
        $allowed = [];
        $result = $this->regex !== []
            ? $this->matchUnifiedRegex($uri, $method, $allowed)
            : $this->matchChunks($uri, $method, $allowed);

        if ($result !== null) {
            return $result;
        }

        // Collect allowed methods for static routes only on miss
        foreach ($this->staticRoutes as $m => $uris) {
            if (isset($uris[$uri])) {
                $allowed[] = $m;
            }
        }

        if ($allowed !== []) {
            throw new MethodNotAllowedException($uri, $method, array_unique($allowed));
        }

        throw new RouteNotFoundException($uri, $method);
    }

    /**
     * Match against unified regex (single pattern per HTTP method).
     *
     * @param string $uri URI to match
     * @param string $method HTTP method
     * @param array $allowed Allowed methods collector (by reference)
     * @return MatchResult|null Match result or null if not matched
     */
    private function matchUnifiedRegex(string $uri, string $method, array &$allowed): ?MatchResult
    {
        if (isset($this->regex[$method]) && preg_match($this->regex[$method], $uri, $m)) {
            $d = $this->routeMap[$method][$m['MARK']];
            return $this->matchResult($d, $this->extractParams($m, $d));
        }

        foreach ($this->regex as $m => $regex) {
            if ($m !== $method && preg_match($regex, $uri)) {
                $allowed[] = $m;
            }
        }

        return null;
    }

    /**
     * Match against chunked regex patterns.
     *
     * Uses prefix index to reduce chunks to search.
     *
     * @param string $uri URI to match
     * @param string $method HTTP method
     * @param array $allowed Allowed methods collector (by reference)
     * @return MatchResult|null Match result or null if not matched
     */
    private function matchChunks(string $uri, string $method, array &$allowed): ?MatchResult
    {
        if (isset($this->dynamicChunks[$method])) {
            $prefix = ($p = strpos($uri, '/', 1)) !== false ? substr($uri, 1, $p - 1) : substr($uri, 1);

            $chunksToSearch = $this->prefixIndex[$method][$prefix]
                ?? $this->prefixIndex[$method]['*']
                ?? array_keys($this->dynamicChunks[$method]);

            foreach ($chunksToSearch as $chunkIndex) {
                if (!isset($this->dynamicChunks[$method][$chunkIndex])) {
                    continue;
                }

                $chunk = $this->dynamicChunks[$method][$chunkIndex];

                if (preg_match($chunk['regex'], $uri, $m)) {
                    $d = $chunk['routeMap'][$m['MARK']];
                    return $this->matchResult($d, $this->extractParams($m, $d));
                }
            }
        }

        foreach ($this->dynamicChunks as $m => $methodChunks) {
            if ($m === $method) {
                continue;
            }
            foreach ($methodChunks as $chunk) {
                if (preg_match($chunk['regex'], $uri)) {
                    $allowed[] = $m;
                    break;
                }
            }
        }

        return null;
    }

    /**
     * Extract matched parameters with type coercion.
     *
     * Numeric strings are converted to integers or floats.
     *
     * @param array $matches Regex matches
     * @param array $routeData Route data with paramNames and defaults
     * @return array<string, mixed> Extracted parameters
     */
    private function extractParams(array $matches, array $routeData): array
    {
        $params = $routeData['defaults'] ?? [];

        foreach ($routeData['paramNames'] as $name) {
            if (isset($matches[$name]) && $matches[$name] !== '') {
                $params[$name] = $this->castParameter($matches[$name]);
            }
        }

        return $params;
    }

    /**
     * Match against non-compiled route collection.
     *
     * Fallback for when routes !== $this. Compiles routes on-the-fly.
     *
     * @param RouteCollectorInterface $routes Route collection
     * @param string $uri URI to match
     * @param string $method HTTP method
     * @return MatchResult Match result
     * @throws MethodNotAllowedException If URI matches but method not allowed
     * @throws RouteNotFoundException If no route matches
     */
    private function matchGeneric(RouteCollectorInterface $routes, string $uri, string $method): MatchResult
    {
        $method = strtoupper($method);
        $uri = '/' . ltrim($uri, '/');
        $allowed = [];

        foreach ($routes as $route) {
            $compiled = $this->compiler->compile(
                $route->path,
                $route->tokens,
                $route->defaults
            );

            if (!$compiled->hasParameters()) {
                if ($route->path === $uri) {
                    if ($route->allow($method)) {
                        return new MatchResult($route->name, $route->handler, $route->middlewares, [], $routes);
                    }
                    array_push($allowed, ...$route->methods);
                }
            } elseif (preg_match('#^' . $compiled->regex . '$#', $uri, $m)) {
                if ($route->allow($method)) {
                    $params = $compiled->defaults;
                    foreach ($compiled->parameterNames() as $name) {
                        if (isset($m[$name]) && $m[$name] !== '') {
                            $params[$name] = $this->castParameter($m[$name]);
                        }
                    }
                    return new MatchResult($route->name, $route->handler, $route->middlewares, $params, $routes);
                }
                array_push($allowed, ...$route->methods);
            }
        }

        if ($allowed !== []) {
            throw new MethodNotAllowedException($uri, $method, array_unique($allowed));
        }
        throw new RouteNotFoundException($uri, $method);
    }

    /**
     * Generate URL for named route.
     *
     * @param RouteCollectorInterface $routes Route collection (should be $this for optimal performance)
     * @param string $name Route name
     * @param array $parameters Route parameters
     * @return string Generated URL
     * @throws RouteNotRegisteredException If route not found
     */
    public function generate(RouteCollectorInterface $routes, string $name, array $parameters = []): string
    {
        if ($routes !== $this) {
            return $routes instanceof GeneratorInterface
                ? $routes->generate($routes, $name, $parameters)
                : $this->generateFromRoute($routes->getRoute($name), $parameters);
        }

        if (!isset($this->routeData[$name])) {
            throw new RouteNotRegisteredException($name);
        }

        $d = $this->routeData[$name];

        if (!$this->syntax->hasParameter($d['path'])) {
            return $d['path'];
        }

        return $this->syntax->buildPath(
            $d['path'],
            $parameters + ($d['defaults'] ?? []),
            $d['tokens'] ?? [],
            $d['optionalParams'] ?? [],
            $name
        );
    }

    /**
     * Generate URL from non-cached route.
     *
     * Compiles route on-the-fly and converts to ColonSyntax.
     *
     * @param RouteRecord $route Route record
     * @param array $parameters Route parameters
     * @return string Generated URL
     */
    private function generateFromRoute(RouteRecord $route, array $parameters): string
    {
        if (!$this->compiler->isParametrized($route->path)) {
            return $route->path;
        }

        $compiled = $this->compiler->compile(
            $route->path,
            $route->tokens,
            $route->defaults
        );

        $colonPath = $this->syntaxConverter->toColonSyntax($route->path);

        return $this->syntax->buildPath(
            $colonPath,
            $parameters + $compiled->defaults,
            $compiled->tokens,
            $compiled->optionalParameters,
            $route->name
        );
    }

    /**
     * Check if route exists by name.
     */
    public function has(string $name): bool
    {
        return isset($this->routeData[$name]);
    }

    /**
     * Get route by name.
     *
     * @throws RouteNotRegisteredException If route not found
     */
    public function getRoute(string $name): RouteRecord
    {
        if (!isset($this->routeData[$name])) {
            throw new RouteNotRegisteredException($name);
        }

        return RouteRecord::fromArray($this->routeData[$name]);
    }

    /**
     * Iterate over all routes.
     *
     * @return Generator<string, RouteRecord>
     */
    public function getIterator(): Generator
    {
        foreach ($this->routeData as $name => $data) {
            yield $name => RouteRecord::fromArray($data);
        }
    }

    /**
     * Get total route count.
     */
    public function count(): int
    {
        return count($this->routeData);
    }

    /**
     * Convert to array of route records.
     *
     * @return array<string, RouteRecord>
     */
    public function toArray(): array
    {
        return array_map(static function ($data) {
            return RouteRecord::fromArray($data);
        }, $this->routeData);
    }
}
